def global_alignment(v, w, reward, mismatch, indel_sigma):

    """

    Uses global alignment to find the alignment between any two strings by applying rewards, mismatch and indel penalties

    Parameters:

    reward -> reward value

    mismatch -> mismatch penalty

    indel_sigma -> indel penalty

    v, w -> two sequences

    Returns:

    Maximum score, alignment sequence 1, and alignment sequence 2 along with indels and mismatches

    """

    # Initialize scoring matrix

    n = len(v)

    m = len(w)

    S = [[0 for j in range(m + 1)] for i in range(n + 1)]

 

    # Initialize first row and column

    for i in range(1, n + 1):

        S[i][0] = S[i - 1][0] - indel_sigma

    for j in range(1, m + 1):

        S[0][j] = S[0][j - 1] - indel_sigma

 

    # Fill in the scoring matrix

    for i in range(1, n + 1):

        for j in range(1, m + 1):

            match = S[i - 1][j - 1] + (reward if v[i - 1] == w[j - 1] else -mismatch)

            delete = S[i - 1][j] - indel_sigma

            insert = S[i][j - 1] - indel_sigma

            S[i][j] = max(match, delete, insert)

 

    # Backtrack to find the optimal alignment

    alignment_1 = []

    alignment_2 = []

    i, j = n, m

 

    while i > 0 or j > 0:

        current_score = S[i][j]

        # Go diagonally

        if i > 0 and j > 0 and (current_score == S[i - 1][j - 1] + (reward if v[i - 1] == w[j - 1] else -mismatch)):

            alignment_1.append(v[i - 1])

            alignment_2.append(w[j - 1])

            i -= 1

            j -= 1

        # Go up (i changes, j remains the same)

        elif i > 0 and (current_score == S[i - 1][j] - indel_sigma):

            alignment_1.append(v[i - 1])

            alignment_2.append('-')

            i -= 1

        # Go left (i remains the same, j changes)

        else:

            alignment_1.append('-')

            alignment_2.append(w[j - 1])

            j -= 1

 

    alignment_1.reverse()

    alignment_2.reverse()

 

    return S[n][m], ''.join(alignment_1), ''.join(alignment_2)

 

###########################################################################

if __name__ == "__main__":

    # Sample test
    #1 1 5
    #TCCAATACCCGTGCCCCGGTTCTTTGCCCCATGAAGGGTCACCTCGCGGATTAGTGTGTAAACTGGTGAAACGTCTTCGAAATGCTTTCCGGCACCAGAGTCACCAGTTGAACGGCGGTGATGCATTTTCCATCCCCGATTCTCTGTGCACATCGAGCTGTAGTCCCGGTGTATTTGATGCGGGAAGCCTGGGAGGCATCAGATTGCAAGAATAGGGGAGAGGGCACATTCTTGTTGTAGTGCACTATGGGGCAATAAGATAATAGTCTCATCTTTATAATCAAACAAGGTGTACGGTTAAAGTTTATACAGCTTGCGAGTGGGATACCGTATCTACCTCCTGTGTCCCCTAGCCCCCGATCGTTTCTCCGAGGGTGTCCGATTTCTAACGCTTCTCTGCTTCGATTGGTAGTGAGGGGTCCGGCTCGCAGAGCCAGTGCGACTGGGGTGAGCAGGACCCAGATTGAAATGAAGATCGGATTGTTGAAACACTATAATTCTGGTCTAGTGGCATACGGCCGAAGGCCTCTGGAACAAATCACCTGCGTGTAGTGCTTATGCGAGACATTAATAACTATCGTCCCACGAATACATAAACACAGCAGACTATAGCTGATAGCATACGTGAACTGTCGGGGAAACACCTTCTTGGGGATCATGAATCTGTTGACCCAGGGCTACGTGAGATCACCGAGTCAGCCACGTCCAACCGTTTGAGTATGCACCAATAGCACAATTTCATAGTCTAATTAGGACTATTATCCAGATACATAGCGTTCTAGCAGATATGAAGTGCACAGAAACGAGCGGACGTTAACAAATCGATGGTCGTACTCTATTCTTCCTGGCTTCAGCACCTTAAGTAAGTTAAGGCGCTATTCCTCGACTGCACCACGGAGG
    #TCCATCTGTACCCGTTCCGAGAGCCCGGTTTGCCCCCTGAAGGCGTGCCAGGTCACGCCTCGCGGATTAGTGTGTAAAGTGGTGAATCGTCTTCGAAATGATTTCCGGCACCAGAGTCACCAGTTGCGGCGGTGATGCATTTTCCAGCCTCGCTCTGCAAAGGCATACCACGTATAATAAGCTGTAGTTACCCTCGCGTTGTATTTCGGAATGCGCGGGCGGGAGCCAGATTGCAAGAATAGGGGCACATTCTTGTCTGGTTGGGTCAATATTCCTGCTAGTCTCATCTTTATAATCAAAGTGTACTGACGACGTTTCCTCCGTACAGCTTCGCTGCGAGCGGGGGTCATATACGGTATCGAAACGAGATCCGGTGTCCCCTAGCCAACACACGGAGGGTGGTCCGATTTCAAGATGAGACTCTCTGCTTCTATTGGTAGTGACTCGATTCCGCAACTGGGGTGAGCGACCCCCCAAATCGACTCAATAAAAGATTGTTGAAAAACTACAATTCCGGTCTGGTAGTTATACGGCCGAACGCCACTGGAACAAATCATGCGTGTAGTGCTTATGCGGACACTATCGGGCGGGAACACCCCATAAACAGAGCAGACTAGCATACGTGAAAGTAGATACACCTTCTGCCGTACCAGCCCTTTAAGTGCACGAATCTGTTGACCCCTACGTGAAATCTCCGAGGCAGCCACGTCCAACCGTTCGATTGTCCACCAATAACACAATTTCATTTTGAGTCTAATTATCCAGGACCATTATCCAGATGCACGTTCTAGCAGATATGAAGTGCAGAGAAACGTGCGGACGTTAGTTATGGCACCGCTCTATCTAACCGTGTCCTGACCGCCGCAGCACGGTATTAAGTAAGTTAAAGGTTGTGGACTGCACCACGGAGG
    reward = 1

    mismatch = 1

    indel_sigma = 5

    v = "TCCAATACCCGTGCCCCGGTTCTTTGCCCCATGAAGGGTCACCTCGCGGATTAGTGTGTAAACTGGTGAAACGTCTTCGAAATGCTTTCCGGCACCAGAGTCACCAGTTGAACGGCGGTGATGCATTTTCCATCCCCGATTCTCTGTGCACATCGAGCTGTAGTCCCGGTGTATTTGATGCGGGAAGCCTGGGAGGCATCAGATTGCAAGAATAGGGGAGAGGGCACATTCTTGTTGTAGTGCACTATGGGGCAATAAGATAATAGTCTCATCTTTATAATCAAACAAGGTGTACGGTTAAAGTTTATACAGCTTGCGAGTGGGATACCGTATCTACCTCCTGTGTCCCCTAGCCCCCGATCGTTTCTCCGAGGGTGTCCGATTTCTAACGCTTCTCTGCTTCGATTGGTAGTGAGGGGTCCGGCTCGCAGAGCCAGTGCGACTGGGGTGAGCAGGACCCAGATTGAAATGAAGATCGGATTGTTGAAACACTATAATTCTGGTCTAGTGGCATACGGCCGAAGGCCTCTGGAACAAATCACCTGCGTGTAGTGCTTATGCGAGACATTAATAACTATCGTCCCACGAATACATAAACACAGCAGACTATAGCTGATAGCATACGTGAACTGTCGGGGAAACACCTTCTTGGGGATCATGAATCTGTTGACCCAGGGCTACGTGAGATCACCGAGTCAGCCACGTCCAACCGTTTGAGTATGCACCAATAGCACAATTTCATAGTCTAATTAGGACTATTATCCAGATACATAGCGTTCTAGCAGATATGAAGTGCACAGAAACGAGCGGACGTTAACAAATCGATGGTCGTACTCTATTCTTCCTGGCTTCAGCACCTTAAGTAAGTTAAGGCGCTATTCCTCGACTGCACCACGGAGG"

    w = "TCCATCTGTACCCGTTCCGAGAGCCCGGTTTGCCCCCTGAAGGCGTGCCAGGTCACGCCTCGCGGATTAGTGTGTAAAGTGGTGAATCGTCTTCGAAATGATTTCCGGCACCAGAGTCACCAGTTGCGGCGGTGATGCATTTTCCAGCCTCGCTCTGCAAAGGCATACCACGTATAATAAGCTGTAGTTACCCTCGCGTTGTATTTCGGAATGCGCGGGCGGGAGCCAGATTGCAAGAATAGGGGCACATTCTTGTCTGGTTGGGTCAATATTCCTGCTAGTCTCATCTTTATAATCAAAGTGTACTGACGACGTTTCCTCCGTACAGCTTCGCTGCGAGCGGGGGTCATATACGGTATCGAAACGAGATCCGGTGTCCCCTAGCCAACACACGGAGGGTGGTCCGATTTCAAGATGAGACTCTCTGCTTCTATTGGTAGTGACTCGATTCCGCAACTGGGGTGAGCGACCCCCCAAATCGACTCAATAAAAGATTGTTGAAAAACTACAATTCCGGTCTGGTAGTTATACGGCCGAACGCCACTGGAACAAATCATGCGTGTAGTGCTTATGCGGACACTATCGGGCGGGAACACCCCATAAACAGAGCAGACTAGCATACGTGAAAGTAGATACACCTTCTGCCGTACCAGCCCTTTAAGTGCACGAATCTGTTGACCCCTACGTGAAATCTCCGAGGCAGCCACGTCCAACCGTTCGATTGTCCACCAATAACACAATTTCATTTTGAGTCTAATTATCCAGGACCATTATCCAGATGCACGTTCTAGCAGATATGAAGTGCAGAGAAACGTGCGGACGTTAGTTATGGCACCGCTCTATCTAACCGTGTCCTGACCGCCGCAGCACGGTATTAAGTAAGTTAAAGGTTGTGGACTGCACCACGGAGG"

# Expected answer =

# -1

#GAGA

#GA-T

    alignment_score, alignment_1, alignment_2 = global_alignment(v, w, reward, mismatch, indel_sigma)

    print(alignment_score)

    print(alignment_1)

    print(alignment_2)